<fieldset class="fieldset create account"
          data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <legend class="legend">
        <span><?php /* @escapeNotVerified */ echo __('Additional Information') ?></span>
    </legend>
    <br>
    <div class="field phone required">
        <label for="phone" class="label">
            <span><?php /* @escapeNotVerified */ echo __('My Attribute') ?></span>
        </label>
        <div class="control">
            <input type="text" name="phone" id="phone"
                   title="<?php /* @escapeNotVerified */ echo __('My Attribute') ?>"
                   class="input-text"
                   data-validate="{required:true}" autocomplete="off">
        </div>
    </div>
</fieldset>